/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import dao.PenggunaDao;
import java.awt.Color;
import javax.swing.JOptionPane;
import services.PenggunaService;

/**
 *
 * @author Lenovo
 */
public class Form_GantiPassword extends javax.swing.JPanel {
    
    private PenggunaService service = new PenggunaDao();
    
    public Form_GantiPassword() {
        initComponents();
        setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_gantiPassword = new javax.swing.JPanel();
        gantiPassword_title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        t_username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t_passLama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t_passBaru = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        gantiPassword_title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        gantiPassword_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gantiPassword_title.setText("GANTI PASSWORD");

        jLabel1.setText("Username");

        t_username.setText("username");
        t_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_usernameFocusLost(evt);
            }
        });

        jLabel2.setText("Password Lama");

        t_passLama.setText("password lama");
        t_passLama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_passLamaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_passLamaFocusLost(evt);
            }
        });

        jLabel3.setText("Password Baru");

        t_passBaru.setText("password baru");
        t_passBaru.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_passBaruFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_passBaruFocusLost(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SUBMIT");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_gantiPasswordLayout = new javax.swing.GroupLayout(pn_gantiPassword);
        pn_gantiPassword.setLayout(pn_gantiPasswordLayout);
        pn_gantiPasswordLayout.setHorizontalGroup(
            pn_gantiPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_gantiPasswordLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gantiPassword_title, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
            .addGroup(pn_gantiPasswordLayout.createSequentialGroup()
                .addGroup(pn_gantiPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_gantiPasswordLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pn_gantiPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_gantiPasswordLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(t_passLama, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_gantiPasswordLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(t_username, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_gantiPasswordLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(t_passBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pn_gantiPasswordLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );
        pn_gantiPasswordLayout.setVerticalGroup(
            pn_gantiPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_gantiPasswordLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(gantiPassword_title)
                .addGap(49, 49, 49)
                .addGroup(pn_gantiPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(t_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pn_gantiPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(t_passLama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pn_gantiPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(t_passBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_gantiPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_gantiPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String user = t_username.getText();
        String passLama = t_passLama.getText();
        String passBaru = t_passBaru.getText();
        
        if (!service.validateOldPassword(user, passLama)){
            JOptionPane.showMessageDialog(null, "Username dan password lama tidak valid");
        }
        if (service.changePassword(user, passLama, passBaru)){
            JOptionPane.showMessageDialog(null, "Password berhasil diubah");
        }
        else{
            JOptionPane.showMessageDialog(null, "Password gagal diubah");
        }
        resetForm();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_usernameFocusGained
        String user = t_username.getText();
        if (user.equals("username")){
            t_username.setText("");
        }
    }//GEN-LAST:event_t_usernameFocusGained

    private void t_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_usernameFocusLost
        String user = t_username.getText();
        if (user.equals("")){
            t_username.setText("username");
        }
    }//GEN-LAST:event_t_usernameFocusLost

    private void t_passLamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_passLamaFocusGained
        String passLama = t_passLama.getText();
        if (passLama.equals("password lama")){
            t_passLama.setText("");
        }
    }//GEN-LAST:event_t_passLamaFocusGained

    private void t_passLamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_passLamaFocusLost
        String passLama = t_passLama.getText();
        if (passLama.equals("")){
            t_passLama.setText("password lama");
        }
    }//GEN-LAST:event_t_passLamaFocusLost

    private void t_passBaruFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_passBaruFocusGained
        String passBaru = t_passBaru.getText();
        if (passBaru.equals("password baru")){
            t_passBaru.setText("");
        }
    }//GEN-LAST:event_t_passBaruFocusGained

    private void t_passBaruFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_passBaruFocusLost
        String passBaru = t_passBaru.getText();
        if (passBaru.equals("")){
            t_passBaru.setText("password baru");
        }
    }//GEN-LAST:event_t_passBaruFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gantiPassword_title;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pn_gantiPassword;
    private javax.swing.JTextField t_passBaru;
    private javax.swing.JTextField t_passLama;
    private javax.swing.JTextField t_username;
    // End of variables declaration//GEN-END:variables

    private void resetForm() {
        t_username.setText("");
        t_passLama.setText("");
        t_passBaru.setText("");
    }
}
