/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import dao.SepatuDao;
import java.util.List;
import javax.swing.JOptionPane;
import models.SepatuModel;
import services.SepatuService;
import table_models.SepatuTableMod;

/**
 *
 * @author Lenovo
 */
public class MasterBarang extends javax.swing.JPanel {

    private SepatuService service = new SepatuDao();
    private SepatuTableMod sTableMod = new SepatuTableMod();
    
    public MasterBarang() {
        initComponents();
        
        tb_dataSepatu.setModel(sTableMod);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        dataBarang = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_dataSepatu = new javax.swing.JTable();
        FormBarang_title = new javax.swing.JLabel();
        addBarang_btn = new javax.swing.JButton();
        deleteBarang_btn = new javax.swing.JButton();
        cancelBarang_btn = new javax.swing.JButton();
        addBarang_field = new javax.swing.JPanel();
        FormBarang_title1 = new javax.swing.JLabel();
        addBarang_btn1 = new javax.swing.JButton();
        cancel_btn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        t_idSepatu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t_namaMerk = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t_namaSepatu = new javax.swing.JTextField();
        t_jenisSepatu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t_warna = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t_ukuran = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        t_harga = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t_stok = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        main_panel.setBackground(new java.awt.Color(255, 255, 255));
        main_panel.setLayout(new java.awt.CardLayout());

        dataBarang.setBackground(new java.awt.Color(255, 255, 255));

        tb_dataSepatu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID SEPATU", "KODE SEPATU", "NAMA SEPATU", "JENIS SEPATU", "WARNA", "UKURAN", "HARGA", "JUMLAH STOK"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_dataSepatu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_dataSepatuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_dataSepatu);

        FormBarang_title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        FormBarang_title.setText("Data Sepatu");

        addBarang_btn.setBackground(new java.awt.Color(0, 255, 51));
        addBarang_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addBarang_btn.setForeground(new java.awt.Color(255, 255, 255));
        addBarang_btn.setText("TAMBAH");
        addBarang_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBarang_btnActionPerformed(evt);
            }
        });

        deleteBarang_btn.setBackground(new java.awt.Color(255, 51, 51));
        deleteBarang_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteBarang_btn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBarang_btn.setText("HAPUS");
        deleteBarang_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBarang_btnActionPerformed(evt);
            }
        });

        cancelBarang_btn.setBackground(new java.awt.Color(255, 255, 0));
        cancelBarang_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelBarang_btn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBarang_btn.setText("BATAL");
        cancelBarang_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBarang_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataBarangLayout = new javax.swing.GroupLayout(dataBarang);
        dataBarang.setLayout(dataBarangLayout);
        dataBarangLayout.setHorizontalGroup(
            dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBarangLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FormBarang_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(dataBarangLayout.createSequentialGroup()
                        .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE)
                            .addGroup(dataBarangLayout.createSequentialGroup()
                                .addComponent(addBarang_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteBarang_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelBarang_btn)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        dataBarangLayout.setVerticalGroup(
            dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBarangLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(FormBarang_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addBarang_btn)
                        .addComponent(deleteBarang_btn))
                    .addComponent(cancelBarang_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addContainerGap())
        );

        main_panel.add(dataBarang, "card2");

        addBarang_field.setBackground(new java.awt.Color(255, 255, 255));

        FormBarang_title1.setBackground(new java.awt.Color(255, 255, 255));
        FormBarang_title1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        FormBarang_title1.setText("Tambah Data Sepatu");

        addBarang_btn1.setBackground(new java.awt.Color(0, 0, 255));
        addBarang_btn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addBarang_btn1.setForeground(new java.awt.Color(255, 255, 255));
        addBarang_btn1.setText("TAMBAH");
        addBarang_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBarang_btn1ActionPerformed(evt);
            }
        });

        cancel_btn1.setBackground(new java.awt.Color(255, 0, 0));
        cancel_btn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancel_btn1.setForeground(new java.awt.Color(255, 255, 255));
        cancel_btn1.setText("BATAL");
        cancel_btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cancel_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btn1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("ID SEPATU");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("NAMA MERK");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("JENIS SEPATU");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("NAMA SEPATU ");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("WARNA");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("UKURAN");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("HARGA");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("JUMLAH STOK");

        javax.swing.GroupLayout addBarang_fieldLayout = new javax.swing.GroupLayout(addBarang_field);
        addBarang_field.setLayout(addBarang_fieldLayout);
        addBarang_fieldLayout.setHorizontalGroup(
            addBarang_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addBarang_fieldLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(addBarang_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FormBarang_title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(addBarang_fieldLayout.createSequentialGroup()
                        .addGroup(addBarang_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addBarang_fieldLayout.createSequentialGroup()
                                .addComponent(addBarang_btn1)
                                .addGap(18, 18, 18)
                                .addComponent(cancel_btn1))
                            .addGroup(addBarang_fieldLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(addBarang_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t_idSepatu)
                                    .addGroup(addBarang_fieldLayout.createSequentialGroup()
                                        .addGroup(addBarang_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addBarang_fieldLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(addBarang_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addBarang_fieldLayout.createSequentialGroup()
                        .addGroup(addBarang_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(765, 837, Short.MAX_VALUE))
                    .addGroup(addBarang_fieldLayout.createSequentialGroup()
                        .addGroup(addBarang_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_warna)
                            .addComponent(t_ukuran)
                            .addComponent(t_harga)
                            .addComponent(t_stok, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(addBarang_fieldLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(t_jenisSepatu))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addBarang_fieldLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(addBarang_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(t_namaMerk)
                    .addComponent(t_namaSepatu))
                .addContainerGap())
        );
        addBarang_fieldLayout.setVerticalGroup(
            addBarang_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addBarang_fieldLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(FormBarang_title1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addBarang_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBarang_btn1)
                    .addComponent(cancel_btn1))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_idSepatu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_namaMerk, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_namaSepatu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_jenisSepatu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_warna, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_ukuran, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        main_panel.add(addBarang_field, "card2");

        add(main_panel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void addBarang_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBarang_btnActionPerformed
        main_panel.removeAll();
        main_panel.repaint();
        main_panel.revalidate();
        
        main_panel.add(addBarang_field);
        main_panel.repaint();
        main_panel.revalidate();
        
        addBarang_btn1.setText("SIMPAN");
        t_idSepatu.setText(service.number());
        t_idSepatu.setEnabled(false);
        
        if(addBarang_btn.getText().equals("UBAH")){
            dataTabel();
        }
    }//GEN-LAST:event_addBarang_btnActionPerformed

    private void deleteBarang_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBarang_btnActionPerformed
        deleteData();
    }//GEN-LAST:event_deleteBarang_btnActionPerformed

    private void cancelBarang_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBarang_btnActionPerformed
          showPanel();
          loadData();
    }//GEN-LAST:event_cancelBarang_btnActionPerformed

    private void tb_dataSepatuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_dataSepatuMouseClicked
        if(addBarang_btn.getText().equals("TAMBAH")){
            addBarang_btn.setText("UBAH");
        }
        deleteBarang_btn.setVisible(true);
        cancelBarang_btn.setVisible(true);
    }//GEN-LAST:event_tb_dataSepatuMouseClicked

    private void cancel_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btn1ActionPerformed
        showPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_cancel_btn1ActionPerformed

    private void addBarang_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBarang_btn1ActionPerformed
        if(addBarang_btn1.getText().equals("TAMBAH")){
            addBarang_btn1.setText("SIMPAN");
            t_idSepatu.setText(service.number());
        }
        else if(addBarang_btn1.getText().equals("SIMPAN")){
            saveData();
        }
        else if(addBarang_btn1.getText().equals("PERBARUI")){
            updateData();
        }
    }//GEN-LAST:event_addBarang_btn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FormBarang_title;
    private javax.swing.JLabel FormBarang_title1;
    private javax.swing.JButton addBarang_btn;
    private javax.swing.JButton addBarang_btn1;
    private javax.swing.JPanel addBarang_field;
    private javax.swing.JButton cancelBarang_btn;
    private javax.swing.JButton cancel_btn1;
    private javax.swing.JPanel dataBarang;
    private javax.swing.JButton deleteBarang_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel main_panel;
    private javax.swing.JTextField t_harga;
    private javax.swing.JTextField t_idSepatu;
    private javax.swing.JTextField t_jenisSepatu;
    private javax.swing.JTextField t_namaMerk;
    private javax.swing.JTextField t_namaSepatu;
    private javax.swing.JTextField t_stok;
    private javax.swing.JTextField t_ukuran;
    private javax.swing.JTextField t_warna;
    private javax.swing.JTable tb_dataSepatu;
    // End of variables declaration//GEN-END:variables

    private void active(){
        t_namaSepatu.setEnabled(true);
        t_jenisSepatu.setEnabled(true);
        t_warna.setEnabled(true);
        t_ukuran.setEnabled(true);
        t_harga.setEnabled(true);
        t_stok.setEnabled(true);
    }
    
    private void loadData() {
        deleteBarang_btn.setVisible(false);
        cancelBarang_btn.setVisible(false);
        List<SepatuModel> list = service.getData();
        sTableMod.setData(list);
    }
    
    private void resetForm() {
        addBarang_btn.requestFocus();
        addBarang_btn.setText("TAMBAH");
//        t_idSepatu.setText("");
        t_namaMerk.setText("");
        t_namaSepatu.setText("");
        t_jenisSepatu.setText("");
        t_warna.setText("");
        t_ukuran.setText("");
        t_harga.setText("");
        t_stok.setText("");
    }
    
    private void deleteData(){
        int index = tb_dataSepatu.getSelectedRow();
        if (index!=-1){
            SepatuModel sModel = sTableMod.getData(tb_dataSepatu.convertRowIndexToModel(index));
            
            if (JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
                service.deleteData(sModel);
                sTableMod.deleteData(index);
                loadData();
                resetForm();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan dihapus");
        }
    }
    
    private boolean inputValidation(){
        boolean valid = false;
        if (t_idSepatu.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Id Sepatu tidak boleh kosong");
        }
        if (t_namaMerk.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Merk tidak boleh kosong");
        }
        else if (t_namaSepatu.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Sepatu tidak boleh kosong");
        }
        else if (t_jenisSepatu.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Jenis Sepatu tidak boleh kosong");
        }
        else if (t_warna.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Warna tidak boleh kosong");
        }
        else if (t_ukuran.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ukuran tidak boleh kosong");
        }
        else if (t_harga.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Harga tidak boleh kosong");
        }
        else if (t_stok.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Stok tidak boleh kosong");
        }
        else{
            valid = true;
        }
        return valid;
    }
    
    private void saveData(){        
        if(inputValidation()==true){
            String id = t_idSepatu.getText();
            String merk = t_namaMerk.getText();
            String nama = t_namaSepatu.getText();
            String jenis = t_jenisSepatu.getText();
            String warna = t_warna.getText();
            int ukuran = Integer.parseInt(t_ukuran.getText());
            double harga = Double.parseDouble(t_harga.getText());
            int stok = Integer.parseInt(t_stok.getText());
            
            SepatuModel sModel = new SepatuModel();
            sModel.setIdSepatu(id);
            sModel.setNameMerk(merk);
            sModel.setNamaSepatu(nama);
            sModel.setJenisSepatu(jenis);
            sModel.setWarna(warna);
            sModel.setUkuran(ukuran);
            sModel.setHarga(harga);
            sModel.setJumlahStok(stok);
            
            service.addData(sModel);
            sTableMod.addData(sModel);
//            sTableMod.updateData(stok, sModel);
            showPanel();
            loadData();
            resetForm();
            
            addBarang_btn.setText("TAMBAH");
        }
    }
    
    private void updateData(){
        int index = tb_dataSepatu.getSelectedRow();
        if (index!=-1){
            SepatuModel sModel = sTableMod.getData(tb_dataSepatu.convertRowIndexToModel(index));
            
            if(inputValidation()==true){
            String id = t_idSepatu.getText();
            String merk = t_namaMerk.getText();
            String nama = t_namaSepatu.getText();
            String jenis = t_jenisSepatu.getText();
            String warna = t_warna.getText();
            int ukuran = Integer.parseInt(t_ukuran.getText());
            double harga = Double.parseDouble(t_harga.getText());
            int stok = Integer.parseInt(t_stok.getText());
            
            SepatuModel sModel1 = new SepatuModel();
            sModel1.setIdSepatu(id);
            sModel1.setNameMerk(merk);
            sModel1.setNamaSepatu(nama);
            sModel1.setJenisSepatu(jenis);
            sModel1.setWarna(warna);
            sModel1.setUkuran(ukuran);
            sModel1.setHarga(harga);
            sModel1.setJumlahStok(stok);
            
            service.updateData(sModel1);
            sTableMod.updateData(index,sModel1);
            loadData();
            resetForm();
            showPanel();
            }
        }
    }
    
    private void showPanel() {
        main_panel.removeAll();
        main_panel.add(new MasterBarang());
        main_panel.repaint();
        main_panel.revalidate();
    }

    private void dataTabel() {
        dataBarang.setVisible(false);
        addBarang_field.setVisible(true);
        
        int index = tb_dataSepatu.getSelectedRow();
        FormBarang_title1.setText("Perbarui Data Sepatu");
        
        t_idSepatu.setEnabled(false);
        t_namaMerk.setEnabled(true);
        
        t_idSepatu.setText(tb_dataSepatu.getModel().getValueAt(index, 1).toString());
        t_namaMerk.setText(tb_dataSepatu.getModel().getValueAt(index, 2).toString());
        t_namaSepatu.setText(tb_dataSepatu.getModel().getValueAt(index, 3).toString());
        t_jenisSepatu.setText(tb_dataSepatu.getModel().getValueAt(index, 4).toString());
        t_warna.setText(tb_dataSepatu.getModel().getValueAt(index, 5).toString());
        t_ukuran.setText(tb_dataSepatu.getModel().getValueAt(index, 6).toString());
        t_harga.setText(tb_dataSepatu.getModel().getValueAt(index, 7).toString());
        t_stok.setText(tb_dataSepatu.getModel().getValueAt(index, 8).toString());
        
        active();   
        addBarang_btn1.setText("PERBARUI");
        cancelBarang_btn.setVisible(true);
    }
}
