/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import dao.DistributorDao;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Insets;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;
import models.DistributorModel;
import services.DistributorService;
import table_models.DistributorTableMod;

/**
 *
 * @author Lenovo
 */
public class MasterDistributor extends javax.swing.JPanel {
    
    private DistributorService service = new DistributorDao();
    private DistributorTableMod disTableMod = new DistributorTableMod();
    
    public MasterDistributor() {
        initComponents();
        
        tb_dataDistributor.setModel(disTableMod);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        dataDistributor = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_dataDistributor = new javax.swing.JTable();
        FormDistributor_title = new javax.swing.JLabel();
        addBarang_btn = new javax.swing.JButton();
        deleteBarang_btn = new javax.swing.JButton();
        cancleBarang_btn = new javax.swing.JButton();
        addDIstributor_field = new javax.swing.JPanel();
        FormBarang_title1 = new javax.swing.JLabel();
        addBarang_btn1 = new javax.swing.JButton();
        cancle_btn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        t_idDistributor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t_namaDistributor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t_TelpDistributor = new javax.swing.JTextField();
        t_alamatDistributor = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        main_panel.setBackground(new java.awt.Color(255, 255, 255));
        main_panel.setLayout(new java.awt.CardLayout());

        dataDistributor.setBackground(new java.awt.Color(255, 255, 255));

        tb_dataDistributor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID DISTRIBUTOR", "NAMA DISTRIBUTOR", "TELP DISTRIBUTOR", "ALAMAT DISTRIBUTOR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_dataDistributor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_dataDistributorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_dataDistributor);

        FormDistributor_title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        FormDistributor_title.setText("Data Distributor");

        addBarang_btn.setBackground(new java.awt.Color(0, 255, 51));
        addBarang_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addBarang_btn.setForeground(new java.awt.Color(255, 255, 255));
        addBarang_btn.setText("TAMBAH");
        addBarang_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBarang_btnActionPerformed(evt);
            }
        });

        deleteBarang_btn.setBackground(new java.awt.Color(255, 51, 51));
        deleteBarang_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteBarang_btn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBarang_btn.setText("HAPUS");
        deleteBarang_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBarang_btnActionPerformed(evt);
            }
        });

        cancleBarang_btn.setBackground(new java.awt.Color(255, 255, 0));
        cancleBarang_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancleBarang_btn.setForeground(new java.awt.Color(255, 255, 255));
        cancleBarang_btn.setText("BATAL");
        cancleBarang_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleBarang_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataDistributorLayout = new javax.swing.GroupLayout(dataDistributor);
        dataDistributor.setLayout(dataDistributorLayout);
        dataDistributorLayout.setHorizontalGroup(
            dataDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataDistributorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(dataDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FormDistributor_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(dataDistributorLayout.createSequentialGroup()
                        .addGroup(dataDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE)
                            .addGroup(dataDistributorLayout.createSequentialGroup()
                                .addComponent(addBarang_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteBarang_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancleBarang_btn)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        dataDistributorLayout.setVerticalGroup(
            dataDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataDistributorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(FormDistributor_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dataDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addBarang_btn)
                        .addComponent(deleteBarang_btn))
                    .addComponent(cancleBarang_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        main_panel.add(dataDistributor, "card2");

        addDIstributor_field.setBackground(new java.awt.Color(255, 255, 255));

        FormBarang_title1.setBackground(new java.awt.Color(255, 255, 255));
        FormBarang_title1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        FormBarang_title1.setText("Tambah Data Distributor");

        addBarang_btn1.setBackground(new java.awt.Color(0, 0, 255));
        addBarang_btn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addBarang_btn1.setForeground(new java.awt.Color(255, 255, 255));
        addBarang_btn1.setText("TAMBAH");
        addBarang_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBarang_btn1ActionPerformed(evt);
            }
        });

        cancle_btn1.setBackground(new java.awt.Color(255, 0, 0));
        cancle_btn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancle_btn1.setForeground(new java.awt.Color(255, 255, 255));
        cancle_btn1.setText("BATAL");
        cancle_btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cancle_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancle_btn1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("ID DISTRIBUTOR");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("NAMA DISTRIBUTOR");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("ALAMAT DISTRIBUTOR");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("TELP DISTRIBUTOR");

        javax.swing.GroupLayout addDIstributor_fieldLayout = new javax.swing.GroupLayout(addDIstributor_field);
        addDIstributor_field.setLayout(addDIstributor_fieldLayout);
        addDIstributor_fieldLayout.setHorizontalGroup(
            addDIstributor_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDIstributor_fieldLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(addDIstributor_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FormBarang_title1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                    .addGroup(addDIstributor_fieldLayout.createSequentialGroup()
                        .addGroup(addDIstributor_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addDIstributor_fieldLayout.createSequentialGroup()
                                .addComponent(addBarang_btn1)
                                .addGap(18, 18, 18)
                                .addComponent(cancle_btn1))
                            .addGroup(addDIstributor_fieldLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(addDIstributor_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t_idDistributor)
                                    .addGroup(addDIstributor_fieldLayout.createSequentialGroup()
                                        .addGroup(addDIstributor_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addDIstributor_fieldLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(addDIstributor_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_alamatDistributor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(t_namaDistributor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(t_TelpDistributor, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        addDIstributor_fieldLayout.setVerticalGroup(
            addDIstributor_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDIstributor_fieldLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(FormBarang_title1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addDIstributor_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBarang_btn1)
                    .addComponent(cancle_btn1))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_idDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_namaDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_TelpDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_alamatDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        main_panel.add(addDIstributor_field, "card2");

        add(main_panel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void addBarang_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBarang_btnActionPerformed
        main_panel.removeAll();
        main_panel.repaint();
        main_panel.revalidate();
        
        main_panel.add(addDIstributor_field);
        main_panel.repaint();
        main_panel.revalidate();
        
        addBarang_btn1.setText("SIMPAN");
        t_idDistributor.setText(service.number());
        t_idDistributor.setEnabled(false);
        
        if(addBarang_btn.getText().equals("UBAH")){
            dataTabel();
        }
    }//GEN-LAST:event_addBarang_btnActionPerformed

    private void deleteBarang_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBarang_btnActionPerformed
        deleteData();
    }//GEN-LAST:event_deleteBarang_btnActionPerformed

    private void cancleBarang_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleBarang_btnActionPerformed
          showPanel();
          loadData();
    }//GEN-LAST:event_cancleBarang_btnActionPerformed

    private void addBarang_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBarang_btn1ActionPerformed
        if(addBarang_btn1.getText().equals("TAMBAH")){
            addBarang_btn1.setText("SIMPAN");
            t_idDistributor.setText(service.number());
        }
        else if(addBarang_btn1.getText().equals("SIMPAN")){
            saveData();
        }
        else if(addBarang_btn1.getText().equals("PERBARUI")){
            updateData();
        }
    }//GEN-LAST:event_addBarang_btn1ActionPerformed

    private void cancle_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancle_btn1ActionPerformed
        showPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_cancle_btn1ActionPerformed

    private void tb_dataDistributorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_dataDistributorMouseClicked
        if(addBarang_btn.getText().equals("TAMBAH")){
            addBarang_btn.setText("UBAH");
        }
        deleteBarang_btn.setVisible(true);
        cancleBarang_btn.setVisible(true);
    }//GEN-LAST:event_tb_dataDistributorMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FormBarang_title1;
    private javax.swing.JLabel FormDistributor_title;
    private javax.swing.JButton addBarang_btn;
    private javax.swing.JButton addBarang_btn1;
    private javax.swing.JPanel addDIstributor_field;
    private javax.swing.JButton cancleBarang_btn;
    private javax.swing.JButton cancle_btn1;
    private javax.swing.JPanel dataDistributor;
    private javax.swing.JButton deleteBarang_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel main_panel;
    private javax.swing.JTextField t_TelpDistributor;
    private javax.swing.JTextField t_alamatDistributor;
    private javax.swing.JTextField t_idDistributor;
    private javax.swing.JTextField t_namaDistributor;
    private javax.swing.JTable tb_dataDistributor;
    // End of variables declaration//GEN-END:variables

    
    private void active(){
        t_TelpDistributor.setEnabled(true);
        t_alamatDistributor.setEnabled(true);
    }
    
    private void loadData() {
        deleteBarang_btn.setVisible(false);
        cancleBarang_btn.setVisible(false);
        List<DistributorModel> list = service.getData();
        disTableMod.setData(list);
    }
    
    private void resetForm() {
        addBarang_btn.requestFocus();
        addBarang_btn.setText("TAMBAH");
        t_idDistributor.setText("");
        t_namaDistributor.setText("");
        t_TelpDistributor.setText("");
        t_alamatDistributor.setText("");
    }
    
    private void deleteData(){
        int index = tb_dataDistributor.getSelectedRow();
        if (index!=-1){
            DistributorModel disModel = disTableMod.getData(tb_dataDistributor.convertRowIndexToModel(index));
            
            if (JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
                service.deleteData(disModel);
                disTableMod.deleteData(index);
                loadData();
                resetForm();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan dihapus");
        }
    }
    
    private boolean inputValidation(){
        boolean valid = false;
        if (t_idDistributor.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Id Distributor tidak boleh kosong");
        }
        if (t_namaDistributor.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Distributor tidak boleh kosong");
        }
        else if (t_TelpDistributor.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Telp Distributor tidak boleh kosong");
        }
        else if (t_alamatDistributor.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Alamat Distributor tidak boleh kosong");
        }
        else{
            valid = true;
        }
        return valid;
    }
    
    private void saveData(){        
        if(inputValidation()==true){
            String id = t_idDistributor.getText();
            String nama = t_namaDistributor.getText();
            String telp = t_TelpDistributor.getText();
            String alamat = t_alamatDistributor.getText();
            
            DistributorModel disModel = new DistributorModel();
            disModel.setIdDistributor(id);
            disModel.setNamaDistributor(nama);
            disModel.setTelpDistributor(telp);
            disModel.setAlamatDistributor(alamat);
            
            service.addData(disModel);
            disTableMod.addData(disModel);
            showPanel();
            loadData();
            resetForm();
            addBarang_btn.setText("TAMBAH");
        }
    }
    
    private void updateData(){
        int index = tb_dataDistributor.getSelectedRow();
        if (index!=-1){
            DistributorModel disModel = disTableMod.getData(tb_dataDistributor.convertRowIndexToModel(index));
            
            if(inputValidation()==true){
                String id = t_idDistributor.getText();
                String nama = t_namaDistributor.getText();
                String telp = t_TelpDistributor.getText();
                String alamat = t_alamatDistributor.getText();
            
                DistributorModel disModel1 = new DistributorModel();
                disModel1.setIdDistributor(id);
                disModel1.setNamaDistributor(nama);
                disModel1.setTelpDistributor(telp);
                disModel1.setAlamatDistributor(alamat);
                
                service.updateData(disModel1);
                disTableMod.updateData(index,disModel1);
                loadData();
                resetForm();
                showPanel();
            }
        }
    }

    private void showPanel() {
        main_panel.removeAll();
        main_panel.add(new MasterDistributor());
        main_panel.repaint();
        main_panel.revalidate();
    }

    private void dataTabel() {
        dataDistributor.setVisible(false);
        addDIstributor_field.setVisible(true);
        
        int index = tb_dataDistributor.getSelectedRow();
        FormBarang_title1.setText("Perbarui Data Distributor");
        
        t_idDistributor.setEnabled(false);
        t_namaDistributor.setEnabled(true);
        
        t_idDistributor.setText(tb_dataDistributor.getModel().getValueAt(index, 1).toString());
        t_namaDistributor.setText(tb_dataDistributor.getModel().getValueAt(index, 2).toString());
        t_TelpDistributor.setText(tb_dataDistributor.getModel().getValueAt(index, 3).toString());
        t_alamatDistributor.setText(tb_dataDistributor.getModel().getValueAt(index, 4).toString());
        
        active();
        addBarang_btn1.setText("PERBARUI");
        cancleBarang_btn.setVisible(true);
    }
}
