/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import dao.PenggunaDao;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Insets;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;
import models.PenggunaModel;
import services.PenggunaService;
import table_models.PenggunaTableMod;

/**
 *
 * @author Lenovo
 */
public class MasterPengguna extends javax.swing.JPanel {
    
    private PenggunaService service = new PenggunaDao();
    private PenggunaTableMod pTableMod = new PenggunaTableMod();

    public MasterPengguna(){
        initComponents();
        
        tb_dataPengguna.setModel(pTableMod);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        dataPengguna = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_dataPengguna = new javax.swing.JTable();
        FormBarang_title = new javax.swing.JLabel();
        addBarang_btn = new javax.swing.JButton();
        deleteBarang_btn = new javax.swing.JButton();
        cancleBarang_btn = new javax.swing.JButton();
        addPengguna_field = new javax.swing.JPanel();
        FormBarang_title1 = new javax.swing.JLabel();
        addBarang_btn1 = new javax.swing.JButton();
        cancle_btn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        t_idPengguna = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t_namaPengguna = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t_username = new javax.swing.JTextField();
        t_pass = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t_telpPengguna = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t_alamatPengguna = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbx_level = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        main_panel.setBackground(new java.awt.Color(255, 255, 255));
        main_panel.setLayout(new java.awt.CardLayout());

        dataPengguna.setBackground(new java.awt.Color(255, 255, 255));

        tb_dataPengguna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID PENGGUNA", "NAMA PENGGUNA", "USERNAME", "PASSWORD", "TELP PENGGUNA", "ALAMAT PENGGUNA", "LEVEL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_dataPengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_dataPenggunaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_dataPengguna);

        FormBarang_title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        FormBarang_title.setText("Data Pengguna");

        addBarang_btn.setBackground(new java.awt.Color(0, 255, 51));
        addBarang_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addBarang_btn.setForeground(new java.awt.Color(255, 255, 255));
        addBarang_btn.setText("TAMBAH");
        addBarang_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBarang_btnActionPerformed(evt);
            }
        });

        deleteBarang_btn.setBackground(new java.awt.Color(255, 51, 51));
        deleteBarang_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteBarang_btn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBarang_btn.setText("HAPUS");
        deleteBarang_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBarang_btnActionPerformed(evt);
            }
        });

        cancleBarang_btn.setBackground(new java.awt.Color(255, 255, 0));
        cancleBarang_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancleBarang_btn.setForeground(new java.awt.Color(255, 255, 255));
        cancleBarang_btn.setText("BATAL");
        cancleBarang_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleBarang_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataPenggunaLayout = new javax.swing.GroupLayout(dataPengguna);
        dataPengguna.setLayout(dataPenggunaLayout);
        dataPenggunaLayout.setHorizontalGroup(
            dataPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPenggunaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(dataPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FormBarang_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(dataPenggunaLayout.createSequentialGroup()
                        .addComponent(addBarang_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteBarang_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancleBarang_btn)
                        .addContainerGap(674, Short.MAX_VALUE))))
        );
        dataPenggunaLayout.setVerticalGroup(
            dataPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPenggunaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(FormBarang_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dataPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addBarang_btn)
                        .addComponent(deleteBarang_btn))
                    .addComponent(cancleBarang_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE))
        );

        main_panel.add(dataPengguna, "card2");

        addPengguna_field.setBackground(new java.awt.Color(255, 255, 255));

        FormBarang_title1.setBackground(new java.awt.Color(255, 255, 255));
        FormBarang_title1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        FormBarang_title1.setText("Tambah Data Pengguna");

        addBarang_btn1.setBackground(new java.awt.Color(0, 0, 255));
        addBarang_btn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addBarang_btn1.setForeground(new java.awt.Color(255, 255, 255));
        addBarang_btn1.setText("TAMBAH");
        addBarang_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBarang_btn1ActionPerformed(evt);
            }
        });

        cancle_btn1.setBackground(new java.awt.Color(255, 0, 0));
        cancle_btn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancle_btn1.setForeground(new java.awt.Color(255, 255, 255));
        cancle_btn1.setText("BATAL");
        cancle_btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cancle_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancle_btn1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("ID PENGGUNA");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("NAMA PENGGUNA");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("PASSWORD");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("USERNAME");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("TELP PENGGUNA");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("ALAMAT PENGGUNA");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("LEVEL");

        cbx_level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Akses Level -", "Owner", "Staff" }));

        javax.swing.GroupLayout addPengguna_fieldLayout = new javax.swing.GroupLayout(addPengguna_field);
        addPengguna_field.setLayout(addPengguna_fieldLayout);
        addPengguna_fieldLayout.setHorizontalGroup(
            addPengguna_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPengguna_fieldLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(addPengguna_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FormBarang_title1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                    .addGroup(addPengguna_fieldLayout.createSequentialGroup()
                        .addGroup(addPengguna_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addPengguna_fieldLayout.createSequentialGroup()
                                .addComponent(addBarang_btn1)
                                .addGap(18, 18, 18)
                                .addComponent(cancle_btn1))
                            .addGroup(addPengguna_fieldLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(addPengguna_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t_idPengguna)
                                    .addGroup(addPengguna_fieldLayout.createSequentialGroup()
                                        .addGroup(addPengguna_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPengguna_fieldLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(addPengguna_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(t_namaPengguna)
                    .addComponent(t_username))
                .addContainerGap())
            .addGroup(addPengguna_fieldLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(addPengguna_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPengguna_fieldLayout.createSequentialGroup()
                        .addGroup(addPengguna_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(765, 785, Short.MAX_VALUE))
                    .addGroup(addPengguna_fieldLayout.createSequentialGroup()
                        .addGroup(addPengguna_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_telpPengguna)
                            .addComponent(t_alamatPengguna)
                            .addComponent(t_pass)
                            .addGroup(addPengguna_fieldLayout.createSequentialGroup()
                                .addComponent(cbx_level, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        addPengguna_fieldLayout.setVerticalGroup(
            addPengguna_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPengguna_fieldLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(FormBarang_title1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPengguna_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBarang_btn1)
                    .addComponent(cancle_btn1))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_idPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_namaPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_telpPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_alamatPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        main_panel.add(addPengguna_field, "card2");

        add(main_panel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void addBarang_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBarang_btnActionPerformed
        main_panel.removeAll();
        main_panel.repaint();
        main_panel.revalidate();
        
        main_panel.add(addPengguna_field);
        main_panel.repaint();
        main_panel.revalidate();
        
        addBarang_btn1.setText("SIMPAN");
        t_idPengguna.setText(service.number());
        t_idPengguna.setEnabled(false);
        
        if(addBarang_btn.getText().equals("UBAH")){
            dataTabel();
        }
    }//GEN-LAST:event_addBarang_btnActionPerformed

    private void deleteBarang_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBarang_btnActionPerformed
        deleteData();
    }//GEN-LAST:event_deleteBarang_btnActionPerformed

    private void cancleBarang_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleBarang_btnActionPerformed
        showPanel();
        loadData();
    }//GEN-LAST:event_cancleBarang_btnActionPerformed

    private void cancle_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancle_btn1ActionPerformed
        showPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_cancle_btn1ActionPerformed

    private void tb_dataPenggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_dataPenggunaMouseClicked
        if(addBarang_btn.getText().equals("TAMBAH")){
            addBarang_btn.setText("UBAH");
        }
        deleteBarang_btn.setVisible(true);
        cancleBarang_btn.setVisible(true);
    }//GEN-LAST:event_tb_dataPenggunaMouseClicked

    private void addBarang_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBarang_btn1ActionPerformed
        if(addBarang_btn1.getText().equals("TAMBAH")){
            addBarang_btn1.setText("SIMPAN");
            t_idPengguna.setText(service.number());
        }
        else if(addBarang_btn1.getText().equals("SIMPAN")){
            saveData();
        }
        else if(addBarang_btn1.getText().equals("PERBARUI")){
            updateData();
        }
    }//GEN-LAST:event_addBarang_btn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FormBarang_title;
    private javax.swing.JLabel FormBarang_title1;
    private javax.swing.JButton addBarang_btn;
    private javax.swing.JButton addBarang_btn1;
    private javax.swing.JPanel addPengguna_field;
    private javax.swing.JButton cancleBarang_btn;
    private javax.swing.JButton cancle_btn1;
    private javax.swing.JComboBox<String> cbx_level;
    private javax.swing.JPanel dataPengguna;
    private javax.swing.JButton deleteBarang_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel main_panel;
    private javax.swing.JTextField t_alamatPengguna;
    private javax.swing.JTextField t_idPengguna;
    private javax.swing.JTextField t_namaPengguna;
    private javax.swing.JTextField t_pass;
    private javax.swing.JTextField t_telpPengguna;
    private javax.swing.JTextField t_username;
    private javax.swing.JTable tb_dataPengguna;
    // End of variables declaration//GEN-END:variables

    private void active(){
        t_username.setEnabled(true);
        t_telpPengguna.setEnabled(true);
        t_alamatPengguna.setEnabled(true);
//        t_level.setEnabled(true);
    } 
   
        private void loadData() {
        deleteBarang_btn.setVisible(false);
        cancleBarang_btn.setVisible(false);
        List<PenggunaModel> list = service.getData();
        pTableMod.setData(list);
    }

    private void dataTabel() {
        dataPengguna.setVisible(false);
        addPengguna_field.setVisible(true);
        
        int index = tb_dataPengguna.getSelectedRow();
        FormBarang_title1.setText("Perbarui Data Pengguna");
        
        t_idPengguna.setEnabled(false);
        t_pass.setEnabled(false);
        t_namaPengguna.setEnabled(true);
        
        t_idPengguna.setText(tb_dataPengguna.getModel().getValueAt(index, 1).toString());
        t_namaPengguna.setText(tb_dataPengguna.getModel().getValueAt(index, 2).toString());
        t_username.setText(tb_dataPengguna.getModel().getValueAt(index, 3).toString());
//        t_pass.setText(tb_dataPengguna.getModel().getValueAt(index, 4).toString());
        t_telpPengguna.setText(tb_dataPengguna.getModel().getValueAt(index, 5).toString());
        t_alamatPengguna.setText(tb_dataPengguna.getModel().getValueAt(index, 6).toString());
        cbx_level.setSelectedItem(tb_dataPengguna.getModel().getValueAt(index, 7).toString());
        
        active();   
        addBarang_btn1.setText("PERBARUI");
        cancleBarang_btn.setVisible(true);
    }

    private void deleteData(){
        int index = tb_dataPengguna.getSelectedRow();
        if (index!=-1){
            PenggunaModel pModel = pTableMod.getData(tb_dataPengguna.convertRowIndexToModel(index));
            
            if (JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
                service.deleteData(pModel);
                pTableMod.deleteData(index);
                loadData();
                resetForm();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan dihapus");
        }
    }
    
        private boolean inputValidation(){
        boolean valid = false;
        if (t_idPengguna.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Id Pengguna tidak boleh kosong");
        }
        if (t_namaPengguna.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Pengguna tidak boleh kosong");
        }
        else if (t_username.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Username tidak boleh kosong");
        }
        else if (t_pass.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Password tidak boleh kosong");
        }
        else if (t_telpPengguna.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Telepon tidak boleh kosong");
        }
        else if (t_alamatPengguna.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Alamat Pengguna boleh kosong");
        }
        else if (cbx_level.getSelectedItem().equals("- Pilih Akses Level -")){
            JOptionPane.showMessageDialog(null, "level harus dipilih");
        }
        else{
            valid = true;
        }
        return valid;
    }
        
        private boolean updateValidation(){
        boolean valid = false;
        if (t_idPengguna.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Id Pengguna tidak boleh kosong");
        }
        if (t_namaPengguna.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Pengguna tidak boleh kosong");
        }
        else if (t_username.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Username tidak boleh kosong");
        }
        else if (t_telpPengguna.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Telepon tidak boleh kosong");
        }
        else if (t_alamatPengguna.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Alamat Pengguna boleh kosong");
        }
        else if (cbx_level.getSelectedItem().equals("- Pilih Akses Level -")){
            JOptionPane.showMessageDialog(null, "level harus dipilih");
        }
        else{
            valid = true;
        }
        return valid;
    }

    private void showPanel() {
        main_panel.removeAll();
        main_panel.add(new MasterPengguna());
        main_panel.repaint();
        main_panel.revalidate();
    }

    private void resetForm() {
        addBarang_btn.requestFocus();
        addBarang_btn.setText("TAMBAH");
        t_idPengguna.setText("");
        t_namaPengguna.setText("");
        t_username.setText("");
//        t_pass.setText("");
        t_telpPengguna.setText("");
        t_alamatPengguna.setText("");
        cbx_level.setSelectedItem("- Pilih Akses Level -");
    }
   
    private void saveData(){        
        if(inputValidation()==true){
            String id = t_idPengguna.getText();
            String nama = t_namaPengguna.getText();
            String user = t_username.getText();
            String pass = t_pass.getText();
            String telp = t_telpPengguna.getText();
            String alamat = t_alamatPengguna.getText();
            String level = cbx_level.getSelectedItem().toString();
            
            PenggunaModel penggunaModel = new PenggunaModel();
            penggunaModel.setIdPengguna(id);
            penggunaModel.setNamaPengguna(nama);
            penggunaModel.setUsername(user);
            penggunaModel.setPassword(pass);
            penggunaModel.setTelpPengguna(telp);
            penggunaModel.setAlamatPengguna(alamat);
            penggunaModel.setLevel(level);
            
            service.addData(penggunaModel);
            pTableMod.addData(penggunaModel);
            showPanel();
            loadData();
            resetForm();
            addBarang_btn.setText("TAMBAH");
        }
    }

    private void updateData(){
        int index = tb_dataPengguna.getSelectedRow();
        if (index!=-1){
            PenggunaModel pModel = pTableMod.getData(tb_dataPengguna.convertRowIndexToModel(index));
            
            if(updateValidation()==true){
            String id = t_idPengguna.getText();
            String nama = t_namaPengguna.getText();
            String user = t_username.getText();
//            String pass = t_pass.getText();
            String telp = t_telpPengguna.getText();
            String alamat = t_alamatPengguna.getText();
            String level = cbx_level.getSelectedItem().toString();
            
            PenggunaModel pModel1 = new PenggunaModel();
            pModel1.setIdPengguna(id);
            pModel1.setNamaPengguna(nama);
            pModel1.setUsername(user);
//            pModel1.setPassword(pass);
            pModel1.setTelpPengguna(telp);
            pModel1.setAlamatPengguna(alamat);
            pModel1.setLevel(level);
            
            service.updateData(pModel1);
            pTableMod.updateData(index,pModel1);
            loadData();
            resetForm();
            showPanel();
            }
        }
    }
}
