/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import dao.DetailPemesananDao;
import dao.PemesananDao;
import dao.SepatuDao;
import dao.TempPemesananDao;
import java.util.List;
import javax.swing.JOptionPane;
import models.DetailPemesananModel;
import models.DistributorModel;
import models.PemesananModel;
import models.PenggunaModel;
import models.SepatuModel;
import models.TempPemesananModel;
import services.DetailPemesananService;
import services.PemesananService;
import services.SepatuService;
import services.TempPemesananService;
import table_models.DetailPemesananTableMod;
import table_models.PemesananTableMod;
import table_models.SepatuTableMod;
import table_models.TempPemesananTableMod;

/**
 *
 * @author Ghita Najmi
 */
public class TransaksiPemesanan extends javax.swing.JPanel {

    private final PemesananService servicePsn = new PemesananDao();
    private final DetailPemesananService dtl_service = new DetailPemesananDao();
    private final TempPemesananService temp_service = new TempPemesananDao();
    private final SepatuService spt_service = new SepatuDao();
    
    private final PemesananTableMod psn_tblModel = new PemesananTableMod();
    private final DetailPemesananTableMod dtl_tblModel = new DetailPemesananTableMod();
    private final TempPemesananTableMod temp_tblModel = new TempPemesananTableMod();
    private final SepatuTableMod spt_tblModel = new SepatuTableMod();
    
    
//    private final int noColumnIndex = 0;
//    private final int noColumnWidth = 50;
    
    
    
    public TransaksiPemesanan(String Id) {
        initComponents();
        
        lb_id.setText(Id);
        tampilDataPemesanan_1.setModel(psn_tblModel);
        tampilDataPemesanan_2.setModel(dtl_tblModel);
        tampilDataPemesanan_3.setModel(temp_tblModel);
//        setColumnWidth();
        loadData();
        loadDataSementara();
        pn_detailPemesanan.setVisible(false);
        lb_id.setVisible(false);
    }
//    private void setColumnWidth(){
//        
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        pn_pemesananBarang = new javax.swing.JPanel();
        tampilDataPemesanan = new javax.swing.JPanel();
        lb_id = new javax.swing.JLabel();
        datapemesanan_title = new javax.swing.JLabel();
        addPemesanan_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tampilDataPemesanan_1 = new javax.swing.JTable();
        pn_detailPemesanan = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tampilDataPemesanan_2 = new javax.swing.JTable();
        dispose_icon = new javax.swing.JLabel();
        DetailTransaksiPemesanan = new javax.swing.JLabel();
        TambahDataPemesanan = new javax.swing.JPanel();
        FormBarang_title1 = new javax.swing.JLabel();
        addBarang_btn1 = new javax.swing.JButton();
        cancle_btn1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tPemesanan = new javax.swing.JPanel();
        t_noPemesanan = new javax.swing.JLabel();
        t_noPemesanan1 = new javax.swing.JLabel();
        noPemesanan_txt = new javax.swing.JTextField();
        tanggal_txt = new javax.swing.JTextField();
        tPemesanan2 = new javax.swing.JPanel();
        t_noPemesanan4 = new javax.swing.JLabel();
        t_noPemesanan5 = new javax.swing.JLabel();
        IdSepatu_txt = new javax.swing.JTextField();
        namaSepatu_txt = new javax.swing.JTextField();
        tBarang_title1 = new javax.swing.JLabel();
        t_noPemesanan7 = new javax.swing.JLabel();
        harga_txt = new javax.swing.JTextField();
        t_noPemesanan8 = new javax.swing.JLabel();
        jumlah_txt = new javax.swing.JTextField();
        t_noPemesanan9 = new javax.swing.JLabel();
        subtotal_txt = new javax.swing.JTextField();
        idsepatu_btn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tampilDataPemesanan_3 = new javax.swing.JTable();
        tPemesanan1 = new javax.swing.JPanel();
        t_noPemesanan2 = new javax.swing.JLabel();
        t_noPemesanan3 = new javax.swing.JLabel();
        Distributor_txt = new javax.swing.JTextField();
        namaDist_txt = new javax.swing.JTextField();
        tDistributor_title = new javax.swing.JLabel();
        dist_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lb_total = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addpemesanan_btn1 = new javax.swing.JButton();
        del_btn = new javax.swing.JButton();
        cel_btn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        main_panel.setBackground(new java.awt.Color(204, 204, 204));
        main_panel.setLayout(new java.awt.CardLayout());

        lb_id.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_id.setText("ID");

        datapemesanan_title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        datapemesanan_title.setText("DATA PEMESANAN BARANG");
        datapemesanan_title.setMaximumSize(new java.awt.Dimension(200, 48));
        datapemesanan_title.setMinimumSize(new java.awt.Dimension(200, 48));
        datapemesanan_title.setPreferredSize(new java.awt.Dimension(200, 48));

        addPemesanan_btn.setBackground(new java.awt.Color(51, 51, 255));
        addPemesanan_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addPemesanan_btn.setForeground(new java.awt.Color(255, 255, 255));
        addPemesanan_btn.setText("TAMBAH");
        addPemesanan_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPemesanan_btnActionPerformed(evt);
            }
        });

        tampilDataPemesanan_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tampilDataPemesanan_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tampilDataPemesanan_1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tampilDataPemesanan_1);

        javax.swing.GroupLayout tampilDataPemesananLayout = new javax.swing.GroupLayout(tampilDataPemesanan);
        tampilDataPemesanan.setLayout(tampilDataPemesananLayout);
        tampilDataPemesananLayout.setHorizontalGroup(
            tampilDataPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilDataPemesananLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(tampilDataPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tampilDataPemesananLayout.createSequentialGroup()
                        .addComponent(datapemesanan_title, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                        .addComponent(lb_id, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tampilDataPemesananLayout.createSequentialGroup()
                        .addComponent(addPemesanan_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(tampilDataPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tampilDataPemesananLayout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        tampilDataPemesananLayout.setVerticalGroup(
            tampilDataPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilDataPemesananLayout.createSequentialGroup()
                .addGroup(tampilDataPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datapemesanan_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tampilDataPemesananLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_id)))
                .addGap(19, 19, 19)
                .addComponent(addPemesanan_btn)
                .addGap(0, 354, Short.MAX_VALUE))
            .addGroup(tampilDataPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tampilDataPemesananLayout.createSequentialGroup()
                    .addGap(121, 121, 121)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addGap(32, 32, 32)))
        );

        tampilDataPemesanan_2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tampilDataPemesanan_2);

        dispose_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AssetImg/close_icon.png"))); // NOI18N
        dispose_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dispose_iconMouseClicked(evt);
            }
        });

        DetailTransaksiPemesanan.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        DetailTransaksiPemesanan.setText("DETAIL PEMESANAN BARANG");

        javax.swing.GroupLayout pn_detailPemesananLayout = new javax.swing.GroupLayout(pn_detailPemesanan);
        pn_detailPemesanan.setLayout(pn_detailPemesananLayout);
        pn_detailPemesananLayout.setHorizontalGroup(
            pn_detailPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_detailPemesananLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pn_detailPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(pn_detailPemesananLayout.createSequentialGroup()
                        .addComponent(DetailTransaksiPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dispose_icon)))
                .addContainerGap())
        );
        pn_detailPemesananLayout.setVerticalGroup(
            pn_detailPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_detailPemesananLayout.createSequentialGroup()
                .addGroup(pn_detailPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_detailPemesananLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DetailTransaksiPemesanan))
                    .addGroup(pn_detailPemesananLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(dispose_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_pemesananBarangLayout = new javax.swing.GroupLayout(pn_pemesananBarang);
        pn_pemesananBarang.setLayout(pn_pemesananBarangLayout);
        pn_pemesananBarangLayout.setHorizontalGroup(
            pn_pemesananBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_detailPemesanan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tampilDataPemesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_pemesananBarangLayout.setVerticalGroup(
            pn_pemesananBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_pemesananBarangLayout.createSequentialGroup()
                .addComponent(tampilDataPemesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_detailPemesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        main_panel.add(pn_pemesananBarang, "card2");

        TambahDataPemesanan.setBackground(new java.awt.Color(255, 255, 255));

        FormBarang_title1.setBackground(new java.awt.Color(255, 255, 255));
        FormBarang_title1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        FormBarang_title1.setText("Tambah Pemesanan");

        addBarang_btn1.setBackground(new java.awt.Color(0, 0, 255));
        addBarang_btn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addBarang_btn1.setForeground(new java.awt.Color(255, 255, 255));
        addBarang_btn1.setText("TAMBAH");
        addBarang_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBarang_btn1ActionPerformed(evt);
            }
        });

        cancle_btn1.setBackground(new java.awt.Color(255, 0, 0));
        cancle_btn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancle_btn1.setForeground(new java.awt.Color(255, 255, 255));
        cancle_btn1.setText("BATAL");
        cancle_btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cancle_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancle_btn1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tPemesanan.setBackground(new java.awt.Color(255, 255, 255));
        tPemesanan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        t_noPemesanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        t_noPemesanan.setText("No. Pemesanan");

        t_noPemesanan1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        t_noPemesanan1.setText("Tanggal");

        javax.swing.GroupLayout tPemesananLayout = new javax.swing.GroupLayout(tPemesanan);
        tPemesanan.setLayout(tPemesananLayout);
        tPemesananLayout.setHorizontalGroup(
            tPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tPemesananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_noPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noPemesanan_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(tPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tPemesananLayout.createSequentialGroup()
                        .addComponent(tanggal_txt)
                        .addGap(12, 12, 12))
                    .addGroup(tPemesananLayout.createSequentialGroup()
                        .addComponent(t_noPemesanan1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(49, Short.MAX_VALUE))))
        );
        tPemesananLayout.setVerticalGroup(
            tPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tPemesananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_noPemesanan)
                    .addComponent(t_noPemesanan1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noPemesanan_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tanggal_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tPemesanan2.setBackground(new java.awt.Color(255, 255, 255));
        tPemesanan2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        t_noPemesanan4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        t_noPemesanan4.setText("ID Sepatu");

        t_noPemesanan5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        t_noPemesanan5.setText("Nama Sepatu");

        tBarang_title1.setBackground(new java.awt.Color(255, 255, 255));
        tBarang_title1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tBarang_title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tBarang_title1.setText("BARANG");
        tBarang_title1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        t_noPemesanan7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        t_noPemesanan7.setText("Harga");

        t_noPemesanan8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        t_noPemesanan8.setText("Jumlah");

        jumlah_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah_txtActionPerformed(evt);
            }
        });
        jumlah_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jumlah_txtKeyReleased(evt);
            }
        });

        t_noPemesanan9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        t_noPemesanan9.setText("SubTotal");

        idsepatu_btn.setText("jButton1");
        idsepatu_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idsepatu_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tPemesanan2Layout = new javax.swing.GroupLayout(tPemesanan2);
        tPemesanan2.setLayout(tPemesanan2Layout);
        tPemesanan2Layout.setHorizontalGroup(
            tPemesanan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tPemesanan2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tPemesanan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaSepatu_txt)
                    .addComponent(tBarang_title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tPemesanan2Layout.createSequentialGroup()
                        .addComponent(IdSepatu_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(idsepatu_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jumlah_txt)
                    .addComponent(harga_txt)
                    .addComponent(subtotal_txt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tPemesanan2Layout.createSequentialGroup()
                        .addGroup(tPemesanan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_noPemesanan4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_noPemesanan5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_noPemesanan7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_noPemesanan8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_noPemesanan9, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tPemesanan2Layout.setVerticalGroup(
            tPemesanan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tPemesanan2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tBarang_title1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(t_noPemesanan4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tPemesanan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdSepatu_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idsepatu_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_noPemesanan5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaSepatu_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_noPemesanan7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(harga_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_noPemesanan8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jumlah_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(t_noPemesanan9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtotal_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        tampilDataPemesanan_3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tampilDataPemesanan_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tampilDataPemesanan_3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tampilDataPemesanan_3);

        tPemesanan1.setBackground(new java.awt.Color(255, 255, 255));
        tPemesanan1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        t_noPemesanan2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        t_noPemesanan2.setText("ID Distributor");

        t_noPemesanan3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        t_noPemesanan3.setText("Nama Distributor");

        Distributor_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Distributor_txtActionPerformed(evt);
            }
        });

        tDistributor_title.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tDistributor_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tDistributor_title.setText("DISTRIBUTOR");
        tDistributor_title.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        dist_btn.setText("jButton1");
        dist_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dist_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tPemesanan1Layout = new javax.swing.GroupLayout(tPemesanan1);
        tPemesanan1.setLayout(tPemesanan1Layout);
        tPemesanan1Layout.setHorizontalGroup(
            tPemesanan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tPemesanan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tPemesanan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tDistributor_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tPemesanan1Layout.createSequentialGroup()
                        .addGroup(tPemesanan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_noPemesanan2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tPemesanan1Layout.createSequentialGroup()
                                .addComponent(Distributor_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dist_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(tPemesanan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaDist_txt)
                            .addGroup(tPemesanan1Layout.createSequentialGroup()
                                .addComponent(t_noPemesanan3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 44, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        tPemesanan1Layout.setVerticalGroup(
            tPemesanan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tPemesanan1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tDistributor_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tPemesanan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_noPemesanan2)
                    .addComponent(t_noPemesanan3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tPemesanan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Distributor_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaDist_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dist_btn))
                .addGap(22, 22, 22))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Total Pesanan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_total, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(311, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_total, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        addpemesanan_btn1.setBackground(new java.awt.Color(0, 0, 255));
        addpemesanan_btn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addpemesanan_btn1.setForeground(new java.awt.Color(255, 255, 255));
        addpemesanan_btn1.setText("TAMBAH");
        addpemesanan_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpemesanan_btn1ActionPerformed(evt);
            }
        });

        del_btn.setBackground(new java.awt.Color(255, 51, 51));
        del_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        del_btn.setForeground(new java.awt.Color(255, 255, 255));
        del_btn.setText("HAPUS");
        del_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_btnActionPerformed(evt);
            }
        });

        cel_btn.setBackground(new java.awt.Color(255, 255, 0));
        cel_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cel_btn.setForeground(new java.awt.Color(255, 255, 255));
        cel_btn.setText("BATAL");
        cel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cel_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tPemesanan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tPemesanan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(del_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(cel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(addpemesanan_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tPemesanan1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tPemesanan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(del_btn)
                            .addComponent(cel_btn))
                        .addGap(12, 12, 12)))
                .addComponent(addpemesanan_btn1)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TambahDataPemesananLayout = new javax.swing.GroupLayout(TambahDataPemesanan);
        TambahDataPemesanan.setLayout(TambahDataPemesananLayout);
        TambahDataPemesananLayout.setHorizontalGroup(
            TambahDataPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TambahDataPemesananLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(TambahDataPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TambahDataPemesananLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(7, 7, 7))
                    .addGroup(TambahDataPemesananLayout.createSequentialGroup()
                        .addGroup(TambahDataPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FormBarang_title1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TambahDataPemesananLayout.createSequentialGroup()
                                .addComponent(addBarang_btn1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancle_btn1)))
                        .addContainerGap(471, Short.MAX_VALUE))))
        );
        TambahDataPemesananLayout.setVerticalGroup(
            TambahDataPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TambahDataPemesananLayout.createSequentialGroup()
                .addComponent(FormBarang_title1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TambahDataPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancle_btn1)
                    .addComponent(addBarang_btn1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        main_panel.add(TambahDataPemesanan, "card2");

        add(main_panel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void addPemesanan_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPemesanan_btnActionPerformed
        main_panel.removeAll();
        main_panel.repaint();
        main_panel.revalidate();

        main_panel.add(TambahDataPemesanan);
        main_panel.repaint();
        main_panel.revalidate();
        
        addBarang_btn1.setText("SIMPAN");
        
        noPemesanan_txt.setEnabled(false);
        tanggal_txt.setEnabled(false);
        
        noPemesanan_txt.setText(servicePsn.number());
        DetailPemesananModel dtPsn = new DetailPemesananModel();
        dtl_service.sumTotal(dtPsn);
        String subtotalStr = Double.toString(dtPsn.getSubtotalPemesanan());
        lb_total.setText(subtotalStr);
        setTanggal();
        
        del_btn.setVisible(false);
        cel_btn.setVisible(false);
        
        
        if(addPemesanan_btn.getText().equals("UBAH")){
            dataTabel();
        }
    }//GEN-LAST:event_addPemesanan_btnActionPerformed

    private void tampilDataPemesanan_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tampilDataPemesanan_1MouseClicked
        int row = tampilDataPemesanan_1.getSelectedRow();
        String id = tampilDataPemesanan_1.getValueAt(row, 0).toString();
        
        pn_detailPemesanan.setVisible(true);
        List<DetailPemesananModel> list = dtl_service.getData(id);
        dtl_tblModel.setData(list);
       
    }//GEN-LAST:event_tampilDataPemesanan_1MouseClicked

    private void cancle_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancle_btn1ActionPerformed
        showPanel();
        loadData();
        //resetForm();
    }//GEN-LAST:event_cancle_btn1ActionPerformed

    private void addBarang_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBarang_btn1ActionPerformed
        if(addBarang_btn1.getText().equals("TAMBAH")){
            addBarang_btn1.setText("SIMPAN");
//            t_idDistributor.setText(service.number());
        }
        else if(addBarang_btn1.getText().equals("SIMPAN")){
            saveData();
        }
    }//GEN-LAST:event_addBarang_btn1ActionPerformed

    private void tampilDataPemesanan_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tampilDataPemesanan_3MouseClicked
        int row = tampilDataPemesanan_3.getSelectedRow();
        
        IdSepatu_txt.setEnabled(false);
        namaSepatu_txt.setEnabled(false);
        harga_txt.setEnabled(false);
        jumlah_txt.setEnabled(false);
        subtotal_txt.setEnabled(false);
        
        IdSepatu_txt.setText(tampilDataPemesanan_3.getModel().getValueAt(row, 0).toString());
        namaSepatu_txt.setText(tampilDataPemesanan_3.getModel().getValueAt(row, 1).toString());
        harga_txt.setText(tampilDataPemesanan_3.getModel().getValueAt(row, 2).toString());
        jumlah_txt.setText(tampilDataPemesanan_3.getModel().getValueAt(row, 3).toString());
        subtotal_txt.setText(tampilDataPemesanan_3.getModel().getValueAt(row, 4).toString());
        
        jumlah_txt.setEnabled(true);
        addpemesanan_btn1.setVisible(false);
        
        del_btn.setVisible(true);
        cel_btn.setVisible(true);
    }//GEN-LAST:event_tampilDataPemesanan_3MouseClicked

    private void dist_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dist_btnActionPerformed
        boolean closable = true;
        data_Distributor datDis = new data_Distributor(null, closable);
        datDis.setVisible(true);
        
        Distributor_txt.setText(datDis.distModel.getIdDistributor());
        namaDist_txt.setText(datDis.distModel.getNamaDistributor());
        
        Distributor_txt.setEnabled(false);
        namaDist_txt.setEnabled(false);
        
        idsepatu_btn.requestFocus();
    }//GEN-LAST:event_dist_btnActionPerformed

    private void idsepatu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idsepatu_btnActionPerformed
        resetForm();
        
        boolean closable = true;
        data_Barang datBrg = new data_Barang(null, closable);
        datBrg.setVisible(true);
        
        IdSepatu_txt.setText(datBrg.sptModel.getIdSepatu());
        namaSepatu_txt.setText(datBrg.sptModel.getNamaSepatu());
        harga_txt.setText(datBrg.sptModel.getHarga().toString());
        
        
        jumlah_txt.requestFocus();
        
        IdSepatu_txt.setEnabled(false);
        namaSepatu_txt.setEnabled(false);
        harga_txt.setEnabled(false);
        
      
    }//GEN-LAST:event_idsepatu_btnActionPerformed

    private void addpemesanan_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpemesanan_btn1ActionPerformed
        String id = IdSepatu_txt.getText();
        String nama = namaSepatu_txt.getText();
        Double harga = Double.parseDouble(harga_txt.getText());
        Integer jumlah = Integer.parseInt(jumlah_txt.getText());
        Double subtotal = Double.parseDouble(subtotal_txt.getText());
        String Status = "Sedang di Pesan";
        
        SepatuModel brg = new SepatuModel();
        DetailPemesananModel detPsn = new DetailPemesananModel();
        PemesananModel psn = new PemesananModel();
        TempPemesananModel tempPsn = new TempPemesananModel();
        
        brg.setIdSepatu(id);
        brg.setNamaSepatu(nama);
        brg.setHarga(harga);
        
        detPsn.setJmlPemesanan(jumlah);
        detPsn.setSubtotalPemesanan(subtotal);
        detPsn.setStatus(Status);
        
        tempPsn.setsModel(brg);
        tempPsn.setDpModel(detPsn);
        
      
        String subtotalStr = Double.toString(subtotal);
        
        
        temp_service.addData(tempPsn);
        dtl_service.sumTotal(detPsn);
        lb_total.setText(subtotalStr);
        
        spt_service.ReduceStokSepatu(id, jumlah);
        
        loadDataSementara();
        
        if (JOptionPane.showConfirmDialog(this, "Mau Tambah Pesanan?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
             resetBarang();
             idsepatu_btn.requestFocus();
                
          }
        else{
            resetBarang();
        }
    }//GEN-LAST:event_addpemesanan_btn1ActionPerformed

    private void del_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_btnActionPerformed
        deleteDataTemp();
        
        String id = IdSepatu_txt.getText();
        Integer jumlah = Integer.parseInt(jumlah_txt.getText());
        
        SepatuModel brg = new SepatuModel();
        DetailPemesananModel detPsn = new DetailPemesananModel();
        PemesananModel psn = new PemesananModel();
        TempPemesananModel tempPsn = new TempPemesananModel();
        
        brg.setIdSepatu(id);
        
        detPsn.setJmlPemesanan(jumlah);
        
        tempPsn.setsModel(brg);
        tempPsn.setDpModel(detPsn);
        
        spt_service.updateStock(id,jumlah);
        
        del_btn.setVisible(false);
        
        addpemesanan_btn1.setVisible(true);
        cel_btn.setVisible(false);
        resetForm();
    }//GEN-LAST:event_del_btnActionPerformed

    private void jumlah_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlah_txtKeyReleased
        double harga, subtotal;
        int jumlah;
        harga = Double.parseDouble(harga_txt.getText());
        jumlah = Integer.parseInt(jumlah_txt.getText());
        String inputCount  = jumlah_txt.getText();
        
        if(inputCount.isEmpty()){
            jumlah = 0;
        }else{
            jumlah = Integer.parseInt(inputCount);
        }
        subtotal = harga * jumlah;
        subtotal_txt.setText(Double.toString(subtotal));
        
        subtotal_txt.setEnabled(false);
    }//GEN-LAST:event_jumlah_txtKeyReleased

    private void jumlah_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlah_txtActionPerformed

    private void Distributor_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Distributor_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Distributor_txtActionPerformed

    private void cel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cel_btnActionPerformed
        
        loadDataSementara();
        resetBarang();
        addpemesanan_btn1.setVisible(true);
        del_btn.setVisible(false);
        cel_btn.setVisible(false);
    }//GEN-LAST:event_cel_btnActionPerformed

    private void dispose_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dispose_iconMouseClicked
        showPanel();
        pn_detailPemesanan.setVisible(false);
        loadData();

    }//GEN-LAST:event_dispose_iconMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DetailTransaksiPemesanan;
    private javax.swing.JTextField Distributor_txt;
    private javax.swing.JLabel FormBarang_title1;
    private javax.swing.JTextField IdSepatu_txt;
    private javax.swing.JPanel TambahDataPemesanan;
    private javax.swing.JButton addBarang_btn1;
    private javax.swing.JButton addPemesanan_btn;
    private javax.swing.JButton addpemesanan_btn1;
    private javax.swing.JButton cancle_btn1;
    private javax.swing.JButton cel_btn;
    private javax.swing.JLabel datapemesanan_title;
    private javax.swing.JButton del_btn;
    private javax.swing.JLabel dispose_icon;
    private javax.swing.JButton dist_btn;
    private javax.swing.JTextField harga_txt;
    private javax.swing.JButton idsepatu_btn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jumlah_txt;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_total;
    private javax.swing.JPanel main_panel;
    private javax.swing.JTextField namaDist_txt;
    private javax.swing.JTextField namaSepatu_txt;
    private javax.swing.JTextField noPemesanan_txt;
    private javax.swing.JPanel pn_detailPemesanan;
    private javax.swing.JPanel pn_pemesananBarang;
    private javax.swing.JTextField subtotal_txt;
    private javax.swing.JLabel tBarang_title1;
    private javax.swing.JLabel tDistributor_title;
    private javax.swing.JPanel tPemesanan;
    private javax.swing.JPanel tPemesanan1;
    private javax.swing.JPanel tPemesanan2;
    private javax.swing.JLabel t_noPemesanan;
    private javax.swing.JLabel t_noPemesanan1;
    private javax.swing.JLabel t_noPemesanan2;
    private javax.swing.JLabel t_noPemesanan3;
    private javax.swing.JLabel t_noPemesanan4;
    private javax.swing.JLabel t_noPemesanan5;
    private javax.swing.JLabel t_noPemesanan7;
    private javax.swing.JLabel t_noPemesanan8;
    private javax.swing.JLabel t_noPemesanan9;
    private javax.swing.JPanel tampilDataPemesanan;
    private javax.swing.JTable tampilDataPemesanan_1;
    private javax.swing.JTable tampilDataPemesanan_2;
    private javax.swing.JTable tampilDataPemesanan_3;
    private javax.swing.JTextField tanggal_txt;
    // End of variables declaration//GEN-END:variables

     private void dataTabel() {
        pn_pemesananBarang.setVisible(false);
        TambahDataPemesanan.setVisible(true);
        
        int row = tampilDataPemesanan_1.getSelectedRow();
        datapemesanan_title.setText("Perbarui Data Pesanan");
        
        noPemesanan_txt.setEnabled(false);
        tanggal_txt.setEnabled(false);
        
//        t_idDistributor.setText(tb_dataDistributor.getModel().getValueAt(index, 1).toString());
//        t_namaDistributor.setText(tb_dataDistributor.getModel().getValueAt(index, 2).toString());
//        t_TelpDistributor.setText(tb_dataDistributor.getModel().getValueAt(index, 3).toString());
//        t_alamatDistributor.setText(tb_dataDistributor.getModel().getValueAt(index, 4).toString());
        
//        active();
        addBarang_btn1.setText("PERBARUI");
        cancle_btn1.setVisible(true);
    }
     
//    private void active(){
//        t_TelpDistributor.setEnabled(true);
//        t_alamatDistributor.setEnabled(true);
//    }

    private void loadData() {
       
        List<PemesananModel> list = servicePsn.getData();
        psn_tblModel.setData(list);
    }
    private void loadDataSementara() {
        List<TempPemesananModel>list = temp_service.getData();
        temp_tblModel.setData(list);
       
    }
    
    private void deleteDataTemp(){
        int index = tampilDataPemesanan_3.getSelectedRow();
        if (index!=-1){
            TempPemesananModel tempModel = temp_tblModel.getData(tampilDataPemesanan_3.convertRowIndexToModel(index));
            
            if (JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
                temp_service.deleteData(tempModel);
                temp_tblModel.deleteData(index);
                loadData();
                //resetForm();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan dihapus");
        }
    }
     
     private void resetForm() {
        addPemesanan_btn.requestFocus();
        addPemesanan_btn.setText("TAMBAH");
        IdSepatu_txt.setText("");
        namaSepatu_txt.setText("");
        harga_txt.setText("");
        jumlah_txt.setText("");
        subtotal_txt.setText("");
    }
   
//    
    private boolean inputValidation(){
        boolean valid = false;
        if (Distributor_txt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Id Distributor tidak boleh kosong");
        }
        if (namaDist_txt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Distributor tidak boleh kosong");
        }
        else if (IdSepatu_txt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Id sepatu tidak boleh kosong");
        }
        else if (jumlah_txt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Jumlah sepatu tidak boleh kosong");
        }
        else{
            valid = true;
        }
        return valid;
    }
//    
    private void saveData(){        
        
            String noPesan = noPemesanan_txt.getText();
            String tglPsn = tanggal_txt.getText();
            String idDis = Distributor_txt.getText();
            String idpeng = lb_id.getText();
            String status = "sedang di pesan";
            Double total = Double.parseDouble(lb_total.getText());
            String idSpt = IdSepatu_txt.getText();
            
            PenggunaModel png = new PenggunaModel();
            DistributorModel dist = new DistributorModel();
            SepatuModel brg = new SepatuModel();
            PemesananModel psn = new PemesananModel();
            DetailPemesananModel detpsn = new DetailPemesananModel();
            
            psn.setNoPemesanan(noPesan);
            psn.setTanggalPemesanan(tglPsn);
            psn.setTotalPemesanan(total);
            png.setIdPengguna(idpeng);
            dist.setIdDistributor(idDis);
            brg.setIdSepatu(idSpt);
            
            psn.setIdPengguna(png);
            psn.setIdDistributor(dist);
            
            
            detpsn.setIdSepatu(brg);
            detpsn.setNoPemesanan(psn);
            detpsn.setStatus(status);
            
            servicePsn.addData(psn);
            dtl_service.addData(detpsn);
            
            dtl_service.tempDelete(detpsn);
            psn_tblModel.addData(psn);
            showPanel();
            loadData();
            resetForm();
            addPemesanan_btn.setText("TAMBAH");  
    }
//    
    private void updateDataTemp(){
        int index = tampilDataPemesanan_3.getSelectedRow();
        if (index!=-1){
            TempPemesananModel tempModel = temp_tblModel.getData(tampilDataPemesanan_3.convertRowIndexToModel(index));
            
            
                String id = IdSepatu_txt.getText();
                String nama = namaSepatu_txt.getText();
                Double harga = Double.parseDouble(harga_txt.getText());
                Integer jumlah = Integer.parseInt(jumlah_txt.getText());
                Double subtotal = Double.parseDouble(subtotal_txt.getText());
            
                SepatuModel spt = new SepatuModel();
                DetailPemesananModel detMod = new DetailPemesananModel();
                TempPemesananModel temp = new TempPemesananModel();
                
                spt.setIdSepatu(id);
                spt.setNamaSepatu(nama);
                spt.setHarga(harga);
                detMod.setJmlPemesanan(jumlah);
                detMod.setSubtotalPemesanan(subtotal);
                
                temp.setsModel(spt);
                temp.setDpModel(detMod);
                
                
                temp_service.updateData(temp);
                temp_tblModel.updateData(index,temp);
                String subtotalStr = Double.toString(temp.getDpModel().getSubtotalPemesanan());
                lb_total.setText(subtotalStr);
                loadDataSementara();
                resetForm();
//                showPanel();
            
        }
    }

    private void showPanel() {
        main_panel.removeAll();
        String Id = lb_id.getText();
        main_panel.add(new TransaksiPemesanan(Id));
        main_panel.repaint();
        main_panel.revalidate();
    }

    private void setTanggal() {
       java.util.Date sekarang = new java.util.Date();
       java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("yyyy-MM-dd");
       tanggal_txt.setText(kal.format(sekarang));
    }

    private void resetBarang() {
        IdSepatu_txt.setText("");
        namaSepatu_txt.setText("");
        harga_txt.setText("");
        jumlah_txt.setText("");
        subtotal_txt.setText("");
        
    }

    private void activeBarang() {
        IdSepatu_txt.setEnabled(true);
        namaSepatu_txt.setEnabled(true);
        harga_txt.setEnabled(true);
        jumlah_txt.setEnabled(true);;
        subtotal_txt.setEnabled(true);
    }

   
}
