/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import View.MasterBarang;
import View.MasterDistributor;
import View.MasterPengguna;
import View.MenuSetting;
import View.TransaksiPemesanan;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;


/**
 *
 * @author Lenovo
 */
public class MenuUtama extends javax.swing.JFrame {

  
    public javax.swing.JPanel getPn_utama() {
        return pn_utama;
    }

    public MenuUtama(String id, String nama, String level2) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        lb_id.setText(id);
        lb_nama.setText(nama);
        lb_level.setText(level2);
      
        
        execute();
    }
    
//        public MenuUtama() {
//        initComponents();
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
//        
//        execute();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_navbar = new javax.swing.JPanel();
        setting_btn = new javax.swing.JButton();
        lb_id = new javax.swing.JLabel();
        pn_sidebar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pn_menu_sidebar = new javax.swing.JPanel();
        lb_nama = new javax.swing.JLabel();
        lb_level = new javax.swing.JLabel();
        pn_content = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pn_navbar.setBackground(new java.awt.Color(51, 102, 255));

        setting_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AssetImg/settings_icon.png"))); // NOI18N
        setting_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setting_btnActionPerformed(evt);
            }
        });

        lb_id.setBackground(new java.awt.Color(255, 255, 255));
        lb_id.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_id.setForeground(new java.awt.Color(255, 255, 255));
        lb_id.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_id.setText("ID");

        javax.swing.GroupLayout pn_navbarLayout = new javax.swing.GroupLayout(pn_navbar);
        pn_navbar.setLayout(pn_navbarLayout);
        pn_navbarLayout.setHorizontalGroup(
            pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_navbarLayout.createSequentialGroup()
                .addContainerGap(856, Short.MAX_VALUE)
                .addGroup(pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(setting_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pn_navbarLayout.setVerticalGroup(
            pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_navbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_id)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(setting_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pn_navbar, java.awt.BorderLayout.PAGE_START);

        pn_sidebar.setBackground(new java.awt.Color(255, 255, 255));
        pn_sidebar.setPreferredSize(new java.awt.Dimension(250, 389));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        pn_menu_sidebar.setBackground(new java.awt.Color(255, 255, 255));
        pn_menu_sidebar.setLayout(new javax.swing.BoxLayout(pn_menu_sidebar, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pn_menu_sidebar);

        lb_nama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_nama.setText("Nama");
        lb_nama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        lb_level.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_level.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_level.setText("Level");
        lb_level.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pn_sidebarLayout = new javax.swing.GroupLayout(pn_sidebar);
        pn_sidebar.setLayout(pn_sidebarLayout);
        pn_sidebarLayout.setHorizontalGroup(
            pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_sidebarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lb_nama, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(lb_level, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        pn_sidebarLayout.setVerticalGroup(
            pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_sidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_level, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))
        );

        getContentPane().add(pn_sidebar, java.awt.BorderLayout.LINE_START);

        pn_content.setBackground(new java.awt.Color(204, 255, 255));

        pn_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pn_contentLayout = new javax.swing.GroupLayout(pn_content);
        pn_content.setLayout(pn_contentLayout);
        pn_contentLayout.setHorizontalGroup(
            pn_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
        );
        pn_contentLayout.setVerticalGroup(
            pn_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );

        getContentPane().add(pn_content, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(982, 577));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        getPn_utama().add(new HomeContent());
        getPn_utama().repaint();
        getPn_utama().revalidate();
    }//GEN-LAST:event_formWindowOpened

    private void setting_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setting_btnActionPerformed
        MenuSetting menu = new MenuSetting(this, true, this);
        
       //menampilkan Jdialog
       Point p = setting_btn.getLocationOnScreen();
       int x = p.x + setting_btn.getWidth() - menu.getWidth();
       int y = p.y + setting_btn.getHeight();
       menu.setLocation(x, y);
       menu.setVisible(true);
    }//GEN-LAST:event_setting_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama("id", "nama", "level2").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_level;
    private javax.swing.JLabel lb_nama;
    private javax.swing.JPanel pn_content;
    private javax.swing.JPanel pn_menu_sidebar;
    private javax.swing.JPanel pn_navbar;
    private javax.swing.JPanel pn_sidebar;
    private javax.swing.JPanel pn_utama;
    private javax.swing.JButton setting_btn;
    // End of variables declaration//GEN-END:variables

    private void execute() {
        ImageIcon iconMaster = new ImageIcon(getClass().getResource("/AssetImg/gift_icon.png"));
        ImageIcon iconTransaksi = new ImageIcon(getClass().getResource("/AssetImg/shoppingcart_icon.png"));
        ImageIcon iconHome = new ImageIcon(getClass().getResource("/AssetImg/home_icon.png"));
        
        
        //SUB MENU MASTER
        ImageIcon iconBarang = new ImageIcon(getClass().getResource("/AssetImg/product_icon.png"));
        ImageIcon iconDistributor = new ImageIcon(getClass().getResource("/AssetImg/suplier_icon.png"));
        ImageIcon iconPengguna = new ImageIcon(getClass().getResource("/AssetImg/user_icon.png"));
        
         MenuItem masterBarang = new MenuItem(null, true, iconBarang, "Data Barang", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                getPn_utama().removeAll();
                getPn_utama().add(new MasterBarang());
                getPn_utama().repaint();
                getPn_utama().revalidate();
            }
        });
         MenuItem masterDistributor = new MenuItem(null, true, iconDistributor, "Data Distributor", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                getPn_utama().removeAll();
                getPn_utama().add(new MasterDistributor());
                getPn_utama().repaint();
                getPn_utama().revalidate();
            }
        });
         
        
        MenuItem masterPengguna = new MenuItem(null, true, iconPengguna, "Data Pengguna", new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
        String levelPengguna = lb_level.getText();
        if (levelPengguna.equals("Owner")){ 
            getPn_utama().removeAll();
            getPn_utama().add(new MasterPengguna());
            getPn_utama().repaint();
            getPn_utama().revalidate();
           }
        }
        });


         
         
         //MENU TRANSAKSI
        
        MenuItem menuMaster = new MenuItem(iconMaster, false, null, "Master", null , masterBarang, masterDistributor, masterPengguna );
        MenuItem menuTransaksi = new MenuItem(iconTransaksi, false, null, "Transaksi", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                getPn_utama().removeAll();
                String Id = lb_id.getText();
                getPn_utama().add(new TransaksiPemesanan(Id));
                getPn_utama().repaint();
                getPn_utama().revalidate();
            }
        } );
        MenuItem menuHome = new MenuItem(iconHome, false, null, "Home", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                getPn_utama().removeAll();
                getPn_utama().add(new HomeContent());
                getPn_utama().repaint();
                getPn_utama().revalidate();
            }
        });
       
        addMenu(menuHome, menuMaster, menuTransaksi);
        
    }
    
    private void addMenu(MenuItem... menu){
        for (int i = 0; i < menu.length; i++){
            pn_menu_sidebar.add(menu[i]);
            ArrayList<MenuItem> subMenu = menu[i].getSubMenu();
            for (MenuItem m : subMenu){
                addMenu(m);
            }
        }
        pn_menu_sidebar.revalidate();
    }

    
}
